/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCandlesRouteImport } from './routes/api/candles'
import { Route as ApiTapeRouteImport } from './routes/api/tape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandlesRoute = ApiCandlesRouteImport.update({
  id: '/api/candles',
  path: '/api/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeRoute = ApiTapeRouteImport.update({
  id: '/api/tape',
  path: '/api/tape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/tape': typeof ApiTapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/tape': typeof ApiTapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/tape': typeof ApiTapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/candles' | '/api/tape'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/candles' | '/api/tape'
  id: '__root__' | '/' | '/api/candles' | '/api/tape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCandlesRoute: typeof ApiCandlesRoute
  ApiTapeRoute: typeof ApiTapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candles': {
      id: '/api/candles'
      path: '/api/candles'
      fullPath: '/api/candles'
      preLoaderRoute: typeof ApiCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape': {
      id: '/api/tape'
      path: '/api/tape'
      fullPath: '/api/tape'
      preLoaderRoute: typeof ApiTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCandlesRoute: ApiCandlesRoute,
  ApiTapeRoute: ApiTapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
